### ISSUE TITLE
How to change configuration for 4GB Memory version?

### ISSUE THREAD

**Issue by robrion-id** [rezaxdi/armbian-tv-allwinner-h6#2]
hi mas,

when i try to compile, the option is only for 2gb memory. how to add/change the configuration for 4gb memory?

**Comment by robrion-id** [comment]
mas, waktu build kok gagal ya, no kernel found

**Comment by rezaxdi** [comment]
Have you tried the current build ? Please try the current build to see if it detects wrong amount of RAM
